### ISSUE TITLE
java.lang.ClassNotFoundException: org.skyscreamer.nevado.jms.message.NevadoTextMessageHessianSerializer

### ISSUE THREAD

**Issue by bapatgeeta** [skyscreamer/nevado#77]
I am getting a weird exception while using Nevado, It is searching for class "org.skyscreamer.nevado.jms.message.NevadoTextMessageHessianSerializer", but there is no such class.
I am using nevado simple text message. Message contents are simple String and completely serializable. 
My application WEB-INF/lib folder does have hessian-4.0.7.jar file in it.

The full stack trace is 
java.lang.ClassNotFoundException: org.skyscreamer.nevado.jms.message.NevadoTextMessageHessianSerializer from BaseClassLoader@1204c3e{VFSClassLoaderPolicy@16d864e{name=vfszip:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/ domain=ClassLoaderDomain@23cfcf{name=vfszip:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/ parentPolicy=AFTER_BUT_JAVA_BEFORE parent=ClassLoaderDomain@8e4805{DefaultDomain}} roots=[MemoryContextHandler@25989259[path= context=vfsmemory://a022o-vqtazp-hrhjb4k7-1-hrhjbhgl-2b real=vfsmemory://a022o-vqtazp-hrhjb4k7-1-hrhjbhgl-2b], ZipEntryHandler@23441700[path=MyApp.war/WEB-INF/classes context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/classes], DelegatingHandler@22069910[path=MyApp.war/WEB-INF/lib/AWSReviewer-soap.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/AWSReviewer-soap.jar], DelegatingHandler@18296193[path=MyApp.war/WEB-INF/lib/XmlSchema-1.4.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/XmlSchema-1.4.jar], DelegatingHandler@11315752[path=MyApp.war/WEB-INF/lib/aopalliance-1.0.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/aopalliance-1.0.jar], DelegatingHandler@30883060[path=MyApp.war/WEB-INF/lib/apache-velocity-velocity-1.5.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/apache-velocity-velocity-1.5.jar], DelegatingHandler@31647828[path=MyApp.war/WEB-INF/lib/aws-java-sdk-1.6.12.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/aws-java-sdk-1.6.12.jar], DelegatingHandler@194894[path=MyApp.war/WEB-INF/lib/aws-soap.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/aws-soap.jar], DelegatingHandler@20811696[path=MyApp.war/WEB-INF/lib/axis.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/axis.jar], DelegatingHandler@10782494[path=MyApp.war/WEB-INF/lib/bcprov-jdk14-131.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/bcprov-jdk14-131.jar], DelegatingHandler@27456022[path=MyApp.war/WEB-INF/lib/cglib.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/cglib.jar], DelegatingHandler@12819932[path=MyApp.war/WEB-INF/lib/commons-beanutils-1.8.0.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/commons-beanutils-1.8.0.jar], DelegatingHandler@11601432[path=MyApp.war/WEB-INF/lib/commons-codec-1.3.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/commons-codec-1.3.jar], DelegatingHandler@469402[path=MyApp.war/WEB-INF/lib/commons-collections.jar context=file:/C:/jboss-5.1.0.GA/server/default/deploy/ real=file:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/WEB-INF/lib/commons-collections.jar], ..... Few more Jars.

Kindly advice. If I have put the issue at in correct place then please direct me towards correct place.

Thank You
Geeta B

**Comment by carterpage** [comment]
There is no such class, never has been.  Maybe search your code for
NevadoTextMessageHessianSerializer?  Also your stack trace is a little odd.
 I don't see an actual calling stack.  Can you see what code is actually
trying to call it?

**Comment by bapatgeeta** [comment]
There is no class called "NevadoTextMessageHessianSerializer" in my source code either.
I have noticed that we get following error "java.lang.ClassNotFoundException: java/util/HashMapHessianSerializer"

Looks like it is attaching "HessianSerializer" for few classes and not been able to find them then.

Apologies for not putting full stack trace
Here it is for "NevadoTextMessageHessianSerializer":
java.lang.ClassNotFoundException: org.skyscreamer.nevado.jms.message.NevadoTextMessageHessianSerializer from BaseClassLoader@1204c3e{VFSClassLoaderPolicy@16d864e{name=vfszip:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/ domain=ClassLoaderDomain@23cfcf{name=vfszip:/C:/jboss-5.1.0.GA/server/default/deploy/MyApp.war/ parentPolicy=AFTER_BUT_JAVA_BEFORE parent=ClassLoaderDomain@8e4805{DefaultDomain}} .... A whole lot of jar files and libraries........
com.lowagie.text.pdf.interfaces, org.springframework.ejb.interceptor] <IMPORT-ALL>NON_EMPTY}}
    at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:448)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.caucho.hessian.io.ContextSerializerFactory.getCustomSerializer(ContextSerializerFactory.java:190)
    at com.caucho.hessian.io.SerializerFactory.loadSerializer(SerializerFactory.java:266)
    at com.caucho.hessian.io.SerializerFactory.getSerializer(SerializerFactory.java:224)
    at com.caucho.hessian.io.SerializerFactory.getObjectSerializer(SerializerFactory.java:197)
    at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:418)
    at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:293)
    at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:212)
    at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:171)
    at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:421)
    at org.skyscreamer.nevado.jms.util.SerializeUtil.serialize(SerializeUtil.java:38)
    at org.skyscreamer.nevado.jms.util.SerializeUtil.serializeToString(SerializeUtil.java:22)
    at org.skyscreamer.nevado.jms.connector.AbstractSQSConnector.serializeMessage(AbstractSQSConnector.java:276)
    at org.skyscreamer.nevado.jms.connector.AbstractSQSConnector.sendMessage(AbstractSQSConnector.java:75)
    at org.skyscreamer.nevado.jms.NevadoSession.sendMessage(NevadoSession.java:416)
    at org.skyscreamer.nevado.jms.NevadoMessageProducer.send(NevadoMessageProducer.java:137)
    at org.skyscreamer.nevado.jms.NevadoMessageProducer.send(NevadoMessageProducer.java:112)
    at org.skyscreamer.nevado.jms.NevadoMessageProducer.send(NevadoMessageProducer.java:100)
    at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:592)
    at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:569)
    at org.springframework.jms.core.JmsTemplate$4.doInJms(JmsTemplate.java:546)
    at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:466)
    at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:543)
    at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:620)
    at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:607)
    at com.MyApp.messages.async.SQSMessaging.sendMessageToQueue(SQSMessaging.java:36)
    at com.MyApp.messages.async.service.AbstractAsyncService.sendMessage(AbstractAsyncService.java:38)
    at com.MyApp.service.impl.ServiceImpl.sendAsyncMessage(ServiceImpl.java:2934)
    at com.MyApp.service.impl.ServiceImpl.sendMessage(ServiceImpl.java:2914)
    at com.MyApp.service.impl.ServiceImpl.handleEvent(ServiceImpl.java:2544)
    at com.MyApp.service.impl.ServiceImpl.processTriggerForAccept(ServiceImpl.java:1809)
    at com.MyApp.service.impl.ServiceImpl.process(ServiceImpl.java:425)
    at com.MyApp.service.endpoint.processEndpoint.process(processEndpoint.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.ws.server.endpoint.MethodEndpoint.invoke(MethodEndpoint.java:115)
    at org.springframework.ws.server.endpoint.adapter.MarshallingMethodEndpointAdapter.invokeInternal(MarshallingMethodEndpointAdapter.java:135)
    at org.springframework.ws.server.endpoint.adapter.AbstractMethodEndpointAdapter.invoke(AbstractMethodEndpointAdapter.java:58)
    at org.springframework.ws.server.MessageDispatcher.dispatch(MessageDispatcher.java:228)
    at org.springframework.ws.server.MessageDispatcher.receive(MessageDispatcher.java:170)
    at org.springframework.ws.transport.support.WebServiceMessageReceiverObjectSupport.handleConnection(WebServiceMessageReceiverObjectSupport.java:88)
    at org.springframework.ws.transport.http.WebServiceMessageReceiverHandlerAdapter.handle(WebServiceMessageReceiverHandlerAdapter.java:57)
    at org.springframework.ws.transport.http.MessageDispatcherServlet.doService(MessageDispatcherServlet.java:230)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:647)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:563)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
    at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
    at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
    at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
    at java.lang.Thread.run(Unknown Source)

Stack trace for "java/util/HashMapHessianSerializer""
2014-02-11 12:28:05,174 ALL   [com.caucho.hessian.io.ContextSerializerFactory](http-0.0.0.0-8080-2) java.lang.ClassNotFoundException: java/util/HashMapHessianSerializer
java.lang.ClassNotFoundException: java/util/HashMapHessianSerializer
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at com.caucho.hessian.io.ContextSerializerFactory.getCustomSerializer(ContextSerializerFactory.java:190)
    at com.caucho.hessian.io.SerializerFactory.loadSerializer(SerializerFactory.java:266)
    at com.caucho.hessian.io.SerializerFactory.getSerializer(SerializerFactory.java:224)
    at com.caucho.hessian.io.SerializerFactory.getObjectSerializer(SerializerFactory.java:197)
    at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:418)
    at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:293)
    at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:212)
    at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:171)
    at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:421)
    at org.skyscreamer.nevado.jms.util.SerializeUtil.serialize(SerializeUtil.java:38)
    at org.skyscreamer.nevado.jms.util.SerializeUtil.serializeToString(SerializeUtil.java:22)
    at org.skyscreamer.nevado.jms.connector.AbstractSQSConnector.serializeMessage(AbstractSQSConnector.java:276)
    at org.skyscreamer.nevado.jms.connector.AbstractSQSConnector.sendMessage(AbstractSQSConnector.java:75)
    at org.skyscreamer.nevado.jms.NevadoSession.sendMessage(NevadoSession.java:416)
    at org.skyscreamer.nevado.jms.NevadoMessageProducer.send(NevadoMessageProducer.java:137)
    at org.skyscreamer.nevado.jms.NevadoMessageProducer.send(NevadoMessageProducer.java:112)
    at org.skyscreamer.nevado.jms.NevadoMessageProducer.send(NevadoMessageProducer.java:100)
    at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:592)
    at org.springframework.jms.core.JmsTemplate.doSend(JmsTemplate.java:569)
    at org.springframework.jms.core.JmsTemplate$4.doInJms(JmsTemplate.java:546)
    at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:466)
    at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:543)
    at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:620)
    at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:607)
    at com.MyApp.messages.async.SQSMessaging.sendMessageToQueue(SQSMessaging.java:36)
    at com.MyApp.messages.async.service.AbstractAsyncService.sendMessage(AbstractAsyncService.java:38)
    at com.MyApp.service.impl.ServiceImpl.sendAsyncMessage(ServiceImpl.java:2934)
    at com.MyApp.service.impl.ServiceImpl.sendMessage(ServiceImpl.java:2914)
    at com.MyApp.service.impl.ServiceImpl.handleEvent(ServiceImpl.java:2544)
    at com.MyApp.service.impl.ServiceImpl.processTriggerForAccept(ServiceImpl.java:1809)
    at com.MyApp.service.impl.ServiceImpl.process(ServiceImpl.java:425)
    at com.MyApp.service.endpoint.processEndpoint.process(processEndpoint.java:176)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.ws.server.endpoint.MethodEndpoint.invoke(MethodEndpoint.java:115)
    at 

Kindly advice.

**Comment by carterpage** [comment]
Please confirm which version of Nevado you are using.

**Comment by carterpage** [comment]
Also, what's your JVM version?

**Comment by bapatgeeta** [comment]
Apologies for delay.
We are using nevado-jms-1.3.0.jar and jdk1.6.0_24.

**Comment by bapatgeeta** [comment]
Hello, 
Is anyone can guide me on this?

**Comment by carterpage** [comment]
I am unable to reproduce this. I'd suggest you walk through a debugger and
figure out where your VM is getting that class from. Let me know if you
find out any additional information.

**Comment by bapatgeeta** [comment]
Thanks for response. We did ran this in debug mode. and what we observed that it is appending HessianSerializer to NevadoText or HashMap under some if else condition.

**Comment by carterpage** [comment]
Can you point me to where this is happening in the code?

**Comment by carterpage** [comment]
(Or even a screenshot of the debugger would help.)

**Comment by bapatgeeta** [comment]
It is clear from stack traced the code is in ContextSerializerFactory.java file.
In following method you can see that it is appending "HessianSerializer"

 Class serClass = Class.forName(cl.getName() + "HessianSerializer",

public Serializer getCustomSerializer(Class cl)
  {
    Serializer serializer = _customSerializerMap.get(cl.getName());

```
if (serializer == AbstractSerializer.NULL)
  return null;
else if (serializer != null)
  return serializer;

try {
  Class serClass = Class.forName(cl.getName() + "HessianSerializer",
                                   false, cl.getClassLoader());

  Serializer ser = (Serializer) serClass.newInstance();

  _customSerializerMap.put(cl.getName(), ser);

  return ser;
} catch (ClassNotFoundException e) {
  log.log(Level.ALL, e.toString(), e);
} catch (Exception e) {
  throw new HessianException(e);
}

_customSerializerMap.put(cl.getName(), AbstractSerializer.NULL);

return null;
```

  }

**Comment by carterpage** [comment]
Quick question: Is anything actually broken or are you just getting the
stack trace in your logs?

**Comment by bapatgeeta** [comment]
Nothing is breaking it post message on queue but leaves hell lot of stack trace each time message is sent or received to increase our logs files.

**Comment by carterpage** [comment]
Interesting.  You're printing out debugging messages from java.util.logging.  It is a shame that Hessian logs this stack trace, even at debug level, but you can make it go away by tightening your logging level for com.caucho.hessian.

Try something like:

```
com.caucho.hessian=CONFIG
```

in your logging.properties file.
